# Generated by Django 5.0.6 on 2025-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accountholderprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholderprofile',
            name='nominee_relationship',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
