# Generated by Django 5.0.6 on 2025-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accountholderprofile_nominee_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholderprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
