# Generated by Django 5.0.6 on 2025-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
