# Generated by Django 5.0.6 on 2025-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_client_pin_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Send', 'Send'), ('Receive', 'Receive'), ('Withdraw', 'Withdraw'), ('Deposit', 'Deposit'), ('Pyament_Send', 'Payment_Send'), ('Payment_Receive', 'Payment_Receive')], max_length=20),
        ),
    ]
